name: docker-ros

on: push
jobs:
  docker-ros:
    runs-on: ubuntu-latest
    steps:
      - uses: ika-rwth-aachen/docker-ros@v1.5.0
        with:
          base-image: ros:humble
          command: ros2 launch yolov5_tc launch.py
          target: run
          image-name: docker.io/raffivk/yolov5_tc
          registry: docker.io
          registry-user: ${{ secrets.REGISTRY_USER }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
